name: Fullstack CI/CD

on:
  push:
    branches: [ "main" ]

jobs:

  build-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Spring Boot
        run: |
          cd demo
          ./mvnw clean package -DskipTests

      - name: Build Docker image (backend)
        run: |
          docker build -t backend ./demo

  build-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install & Build Vue
        run: |
          cd project-vue
          npm install
          npm run build

      - name: Build Docker image (frontend)
        run: |
          docker build -t frontend ./project-vue

  docker-push:
    needs: [build-backend, build-frontend]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build & Push backend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/backend ./demo
          docker push ${{ secrets.DOCKER_USERNAME }}/backend

      - name: Build & Push frontend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend ./project-vue
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend